const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const planets=[['XUNIA PRIME','Home'],['DEV-1','Development'],['DAO-3','Governance'],['AI-7','Research'],['BUILD-9','Production']];
const defaults=[
  ['Pushed 3 commits to MMGISxunia-','2 minutes ago','+150 XP'],
  ['Merged pull request #42','1 hour ago','+500 XP'],
  ['Created new repository','3 hours ago','+300 XP'],
  ['Released v1.2.0','5 hours ago','+1,000 XP'],
  ['Closed issue #87','1 day ago','+200 XP']
];
function setTab(name){$$('.xunia-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='LIVE EARTH')$('#earthBtn')?.click();if(name==='MULTIVERSE')$('#universeBtn')?.click();if(!['LIVE EARTH','MULTIVERSE'].includes(name)){const meta=$('#worldMeta');const title=$('#worldTitle');if(title)title.textContent=name;if(meta)meta.textContent='XUNIAVERSE COMMAND MODULE // INTERACTIVE VIEW';}}
function renderPlanets(){const root=$('#planetStrip');if(!root)return;const custom=JSON.parse(localStorage.getItem('xunia.planets')||'[]');const all=[...planets,...custom.map(p=>[p.name,p.role||'Custom'])];root.innerHTML=all.map((p,i)=>`<button class="planet-node ${i===0?'active':''}" data-planet="${p[0]}"><span class="planet-orb"></span><b>${p[0]}</b><small>(${p[1]})</small></button>`).join('')+`<button class="planet-create" id="createPlanetBtn">+ CREATE PLANET</button>`;$$('.planet-node').forEach(b=>b.addEventListener('click',()=>{$$('.planet-node').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#worldTitle').textContent=b.dataset.planet;$('#worldMeta').textContent='CIVILIZATION WORLD // GITHUB-LINKED PLANETARY NODE';}));$('#createPlanetBtn')?.addEventListener('click',()=>$('#planetModal')?.classList.add('open'));}
function renderActivity(items=defaults){const root=$('#activityList');if(!root)return;root.innerHTML=items.map(x=>`<div class="activity-row"><div><b>${x[0]}</b><span>${x[1]}</span></div><span class="activity-xp">${x[2]}</span></div>`).join('');}
function bindSearch(){const input=$('#globalSearch');if(!input)return;input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=input.value.trim().toLowerCase();const layer=[...document.querySelectorAll('.layer-chip')].find(x=>x.textContent.toLowerCase().includes(q));if(layer){layer.scrollIntoView({behavior:'smooth',block:'center'});layer.animate([{boxShadow:'0 0 0 0 #56ddff'},{boxShadow:'0 0 22px 2px #56ddff'},{boxShadow:'0 0 0 0 #56ddff'}],{duration:900});}else{$('#worldTitle').textContent=input.value.toUpperCase()||'XUNIA PRIME';$('#worldMeta').textContent='SEARCH // ENTITY OR SYSTEM QUERY';}});}
function bindModal(){$('#planetCancel')?.addEventListener('click',()=>$('#planetModal')?.classList.remove('open'));$('#planetSave')?.addEventListener('click',()=>{const name=$('#planetName')?.value.trim();if(!name)return;const role=$('#planetRole')?.value.trim()||'Custom';const arr=JSON.parse(localStorage.getItem('xunia.planets')||'[]');arr.push({name:name.toUpperCase(),role});localStorage.setItem('xunia.planets',JSON.stringify(arr));$('#planetModal').classList.remove('open');renderPlanets();});}
function bindGithub(){window.addEventListener('xunia:github-civilization',e=>{const s=e.detail||{};$('#civEra').textContent=s.era||'FOUNDATION';$('#civScore').textContent=(s.totalScore||0).toLocaleString();$('#repoCount').textContent=s.repositoryCount||0;const stars=(s.colonies||[]).reduce((a,r)=>a+(r.stars||0),0);const forks=(s.colonies||[]).reduce((a,r)=>a+(r.forks||0),0);$('#starCount').textContent=stars.toLocaleString();$('#forkCount').textContent=forks.toLocaleString();const pct=Math.max(8,Math.min(100,((s.totalScore||0)%1200)/12));$('#xpFill').style.width=`${pct}%`;const recent=(s.colonies||[]).slice(0,5).map((r,i)=>[`Developed ${r.name}`,i===0?'latest sync':`${i+1} colony cycles ago`,`+${Math.max(50,Math.round((r.score||50)/2))} XP`]);if(recent.length)renderActivity(recent);});$('#syncGithub')?.addEventListener('click',()=>location.reload());}
function boot(){renderPlanets();renderActivity();bindSearch();bindModal();bindGithub();$$('.xunia-nav button').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));$('#viewCivilization')?.addEventListener('click',()=>setTab('CIVILIZATIONS'));}
document.addEventListener('DOMContentLoaded',boot);