const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const S={viewer:null,selected:null,sensor:'normal',detection:false,scope:false,director:false,drawMode:null,drawPoints:[],drawEntities:[],interactionHandler:null,detectionLayer:null,lastDetection:0,drawer:'contacts',mapStyle:'osm',photoreal:null,refreshing:false};
const layerAlias={flight:'flights',flights:'flights',aircraft:'flights',earthquake:'earthquakes',earthquakes:'earthquakes',quake:'earthquakes',fires:'fires',fire:'fires',satellite:'sat_military',satellites:'sat_military',ships:'maritime',ship:'maritime',maritime:'maritime',news:'live_news',weather:'weather',incident:'global_incidents',incidents:'global_incidents',launch:'launches',launches:'launches',radio:'radio',bikes:'bikeshare',bikeshare:'bikeshare',traffic:'traffic',cctv:'cctv',camera:'cctv',cameras:'cctv'};
const sensorModes=['normal','crt','nvg','flir','iron','noir','snow'];
function toast(message){const el=$('#supToast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function readout(title,sub=''){const el=$('#supModeReadout');if(!el)return;el.innerHTML=`<b>${title}</b><span>${sub}</span>`}
function getViewer(){return S.viewer||window.__XUNIA_VIEWER__||null}
function waitViewer(timeout=5000){const v=getViewer();if(v)return Promise.resolve(v);return new Promise((resolve,reject)=>{const t=setTimeout(()=>{window.removeEventListener('xunia:viewer-ready',onReady);reject(new Error('Earth viewer did not initialize'))},timeout);function onReady(e){clearTimeout(t);resolve(e.detail)}window.addEventListener('xunia:viewer-ready',onReady,{once:true})})}
async function ensureEarth(){if(!getViewer())$('#earthBtn')?.click();const v=await waitViewer();if(!S.viewer)attachViewer(v);return v}
function prop(entity,key){const value=entity?.properties?.[key];try{return value?.getValue?value.getValue(Cesium.JulianDate.now()):value}catch{return value}}
function labelFor(entity){return String(prop(entity,'title')||prop(entity,'callsign')||prop(entity,'name')||prop(entity,'id')||entity?.name||entity?.id||'CONTACT')}
function layerFor(entity){return String(prop(entity,'layerId')||prop(entity,'_feed')||'CONTACT').toUpperCase()}
function posFor(entity){try{return entity?.position?.getValue(Cesium.JulianDate.now())||null}catch{return null}}
function cameraCenterCartographic(viewer){const canvas=viewer.scene.canvas;const p=viewer.camera.pickEllipsoid(new Cesium.Cartesian2(canvas.clientWidth/2,canvas.clientHeight/2),viewer.scene.globe.ellipsoid);return p?Cesium.Cartographic.fromCartesian(p):viewer.camera.positionCartographic}
function distanceKm(a,b){try{const g=new Cesium.EllipsoidGeodesic(a,b);return g.surfaceDistance/1000}catch{return Infinity}}
function entityCartographic(entity){const p=posFor(entity);return p?Cesium.Cartographic.fromCartesian(p):null}
function flyEntity(entity,height=120000){const c=entityCartographic(entity);if(!c)return;getViewer()?.camera.flyTo({destination:Cesium.Cartesian3.fromRadians(c.longitude,c.latitude,Math.max(height,c.height+height)),duration:1.25})}
function selectEntity(entity){const viewer=getViewer();if(!viewer||!entity)return;S.selected=entity;viewer.selectedEntity=entity;readout(labelFor(entity),`${layerFor(entity)} // SELECTED`);renderContacts()}
function attachViewer(viewer){if(!viewer||S.viewer===viewer)return;S.viewer=viewer;viewer.targetFrameRate=60;S.detectionLayer=$('#supDetection');const h=S.interactionHandler=new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);h.setInputAction(click=>{if(S.drawMode){handleGeoClick(click.position);return}const picked=viewer.scene.pick(click.position);if(picked?.id)selectEntity(picked.id)},Cesium.ScreenSpaceEventType.LEFT_CLICK);h.setInputAction(()=>finishDrawing(),Cesium.ScreenSpaceEventType.RIGHT_CLICK);viewer.scene.postRender.addEventListener(updateDetection);restoreShareState();setBasemap(S.mapStyle);readout('LIVE EARTH READY','XUNIA GEOSPATIAL ENGINE');}
window.addEventListener('xunia:viewer-ready',e=>attachViewer(e.detail));if(window.__XUNIA_VIEWER__)attachViewer(window.__XUNIA_VIEWER__);

function setSensor(mode){mode=sensorModes.includes(mode)?mode:'normal';S.sensor=mode;const c=$('#cesium');sensorModes.forEach(m=>c?.classList.remove(`sup-${m}`));if(mode!=='normal')c?.classList.add(`sup-${mode}`);$$('[data-sensor]').forEach(b=>b.classList.toggle('active',b.dataset.sensor===mode));$('#sensorName')&&( $('#sensorName').textContent=mode.toUpperCase());readout(`SENSOR // ${mode.toUpperCase()}`,'SIMULATED DISPLAY FILTER');syncSupState();}
function toggleDetection(){S.detection=!S.detection;$('#supDetect')?.classList.toggle('active',S.detection);if(S.detection){ensureEarth().then(()=>toast('Detection overlay enabled'))}else if(S.detectionLayer)S.detectionLayer.innerHTML='';syncSupState()}
function updateDetection(){if(!S.detection||!S.viewer||!S.detectionLayer)return;const now=performance.now();if(now-S.lastDetection<180)return;S.lastDetection=now;const viewer=S.viewer,canvas=viewer.scene.canvas;const rows=[];for(const e of viewer.entities.values.slice(0,240)){const p=posFor(e);if(!p)continue;const win=Cesium.SceneTransforms.worldToWindowCoordinates(viewer.scene,p);if(!win||win.x<0||win.y<0||win.x>canvas.clientWidth||win.y>canvas.clientHeight)continue;rows.push(`<div class="sup-detect-box" style="left:${win.x}px;top:${win.y}px"><span>${escape(labelFor(e))}</span></div>`);if(rows.length>=72)break}S.detectionLayer.innerHTML=rows.join('')}
function escape(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

async function renderContacts(){const drawer=$('#supDrawerBody');if(!drawer||S.drawer!=='contacts')return;const viewer=await ensureEarth().catch(()=>null);if(!viewer)return;const center=cameraCenterCartographic(viewer);const contacts=[];for(const e of viewer.entities.values){const c=entityCartographic(e);if(!c)continue;const km=distanceKm(center,c);contacts.push({e,km})}contacts.sort((a,b)=>a.km-b.km);const limited=contacts.slice(0,36);$('#supDrawerCount')&&($('#supDrawerCount').textContent=`${limited.length} NEAREST`);drawer.innerHTML=limited.map((x,i)=>`<div class="sup-contact" data-contact="${i}"><div><b>${escape(labelFor(x.e))}</b><span>${escape(layerFor(x.e))}</span></div><i>${x.km.toFixed(x.km<10?1:0)} KM</i></div>`).join('')||'<div class="empty-state"><b>NO CONTACTS</b><span>Enable live layers.</span></div>';[...drawer.querySelectorAll('[data-contact]')].forEach(el=>el.onclick=()=>{const x=limited[Number(el.dataset.contact)];selectEntity(x.e);flyEntity(x.e,180000)})}
function openDrawer(type='contacts'){S.drawer=type;const d=$('#supDrawer');d?.classList.add('open');if(type==='contacts')renderContacts();if(type==='bookmarks')renderBookmarks();}
function closeDrawer(){$('#supDrawer')?.classList.remove('open')}
async function trackSelected(){const viewer=await ensureEarth();const e=S.selected||viewer.selectedEntity;if(!e)return toast('Select a contact first');viewer.trackedEntity=e;selectEntity(e);toast(`Tracking ${labelFor(e)}`);readout('TRACK LOCK',labelFor(e))}
async function cockpit(){const viewer=await ensureEarth();const e=S.selected||viewer.selectedEntity;if(!e)return toast('Select an aircraft/contact first');viewer.trackedEntity=e;const c=entityCartographic(e);if(c){const altitude=Number(prop(e,'altitude')||prop(e,'baro_altitude')||c.height||1000);const heading=Cesium.Math.toRadians(Number(prop(e,'heading')||prop(e,'track')||0));viewer.camera.flyTo({destination:Cesium.Cartesian3.fromRadians(c.longitude,c.latitude,Math.max(altitude+350,850)),orientation:{heading,pitch:Cesium.Math.toRadians(-8),roll:0},duration:1.1})}readout('COCKPIT // FOLLOW',labelFor(e));toast('Cockpit follow engaged')}

async function setGlobalContext(){await ensureEarth();const ids=['flights','maritime','sat_military','earthquakes','fires','weather','live_news','global_incidents'];for(const id of ids){const b=$(`[data-layer="${id}"]`);if(b&&!b.classList.contains('active'))b.click()}toast('Global context enabled');readout('GLOBAL CONTEXT','PUBLIC/PASSIVE LAYERS')}
function toggleScope(){S.scope=!S.scope;$('.stage')?.classList.toggle('sup-scope',S.scope);$('#supScope')?.classList.toggle('active',S.scope);syncSupState()}
function toggleHud(){document.body.classList.toggle('sup-hud-off');syncSupState()}
function toggleDirector(){S.director=!S.director;$('#supDirector')?.classList.toggle('active',S.director);readout(S.director?'SCENE DIRECTOR':'SCENE DIRECTOR OFF',S.director?'CINEMATIC ORBIT':'MANUAL CAMERA');directorLoop()}
function directorLoop(){if(!S.director)return;const v=getViewer();if(v&&$('#cesium')&&!$('#cesium').classList.contains('hidden')){try{v.camera.rotateRight(.00055)}catch{}}requestAnimationFrame(directorLoop)}
async function toggle2D3D(){const v=await ensureEarth();if(v.scene.mode===Cesium.SceneMode.SCENE2D){v.scene.morphTo3D(1);toast('3D globe')}else{v.scene.morphTo2D(1);toast('2D map')}}

function beginDraw(mode){ensureEarth().then(()=>{S.drawMode=mode;S.drawPoints=[];$('#supAnnotate')?.classList.add('open');$('#supAnnotateLabel')&&($('#supAnnotateLabel').textContent=mode==='measure'?'MEASURE: CLICK TWO POINTS':'DRAW: CLICK POINTS // RIGHT CLICK TO FINISH');toast(mode==='measure'?'Measurement armed':'Annotation drawing armed')})}
function groundPoint(screen){const v=getViewer();if(!v)return null;return v.camera.pickEllipsoid(screen,v.scene.globe.ellipsoid)}
function handleGeoClick(screen){const p=groundPoint(screen);if(!p)return;S.drawPoints.push(p);const v=getViewer();if(S.drawMode==='measure'){v.entities.add({position:p,point:{pixelSize:7,color:Cesium.Color.CYAN,disableDepthTestDistance:Number.POSITIVE_INFINITY}});if(S.drawPoints.length===2){const a=Cesium.Cartographic.fromCartesian(S.drawPoints[0]),b=Cesium.Cartographic.fromCartesian(S.drawPoints[1]);const g=new Cesium.EllipsoidGeodesic(a,b);const km=g.surfaceDistance/1000;const line=v.entities.add({polyline:{positions:[...S.drawPoints],width:2,material:Cesium.Color.CYAN}});S.drawEntities.push(line);toast(`${km.toFixed(km<10?2:1)} km`);readout('MEASUREMENT',`${km.toFixed(2)} KM`);finishDrawing()}return}const e=v.entities.add({position:p,point:{pixelSize:6,color:Cesium.Color.CYAN}});S.drawEntities.push(e);if(S.drawPoints.length>1){const line=v.entities.add({polyline:{positions:[...S.drawPoints],width:2,material:Cesium.Color.CYAN.withAlpha(.8),clampToGround:false}});S.drawEntities.push(line)}}
function finishDrawing(){if(!S.drawMode)return;const mode=S.drawMode;S.drawMode=null;$('#supAnnotate')?.classList.remove('open');if(mode==='draw'&&S.drawPoints.length>=3){const v=getViewer();const poly=v.entities.add({polygon:{hierarchy:[...S.drawPoints],material:Cesium.Color.CYAN.withAlpha(.08),outline:true,outlineColor:Cesium.Color.CYAN}});S.drawEntities.push(poly)}S.drawPoints=[]}
function clearAnnotations(){const v=getViewer();for(const e of S.drawEntities)v?.entities.remove(e);S.drawEntities=[];S.drawPoints=[];S.drawMode=null;$('#supAnnotate')?.classList.remove('open');toast('Annotations cleared')}

function setBasemap(style){const v=getViewer();if(!v)return;S.mapStyle=style;const layers=v.imageryLayers;layers.removeAll();if(style==='satellite')layers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',credit:'Tiles © Esri',maximumLevel:19}));else layers.addImageryProvider(new Cesium.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',credit:'© OpenStreetMap contributors',maximumLevel:19}));toast(style==='satellite'?'Satellite imagery':'OpenStreetMap')}
async function toggleBasemap(){await ensureEarth();setBasemap(S.mapStyle==='osm'?'satellite':'osm')}
async function geocode(query){query=String(query||'').trim();if(!query)return;const v=await ensureEarth();const local=v.entities.values.find(e=>labelFor(e).toLowerCase().includes(query.toLowerCase()));if(local){selectEntity(local);flyEntity(local,250000);return toast(`Found contact: ${labelFor(local)}`)}try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(query)}`);const data=await r.json();if(!r.ok||!data?.length)throw new Error('No result');const hit=data[0];v.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(Number(hit.lon),Number(hit.lat),180000),duration:1.4});readout('PLACE SEARCH',hit.display_name||query);toast(hit.display_name||query)}catch(e){toast(`Search: ${e.message}`)}}

function cameraState(){const v=getViewer();if(!v)return null;const c=v.camera.positionCartographic;return[Cesium.Math.toDegrees(c.longitude),Cesium.Math.toDegrees(c.latitude),c.height,Cesium.Math.toDegrees(v.camera.heading),Cesium.Math.toDegrees(v.camera.pitch),Cesium.Math.toDegrees(v.camera.roll)].map((n,i)=>i<2?n.toFixed(6):i===2?Math.round(n):n.toFixed(2)).join(',')}
function syncSupState(){const q=new URLSearchParams(location.search);q.set('sensor',S.sensor);if(S.detection)q.set('detect','1');else q.delete('detect');if(S.scope)q.set('scope','1');else q.delete('scope');if(document.body.classList.contains('sup-hud-off'))q.set('hud','0');else q.delete('hud');history.replaceState(null,'',`${location.pathname}?${q}`)}
async function shareView(){await ensureEarth();const q=new URLSearchParams(location.search);const cam=cameraState();if(cam)q.set('cam',cam);q.set('view','earth');q.set('sensor',S.sensor);if(S.detection)q.set('detect','1');if(S.scope)q.set('scope','1');const url=`${location.origin}${location.pathname}?${q}`;try{await navigator.clipboard.writeText(url);toast('Share link copied')}catch{prompt('Copy share link',url)}}
function restoreShareState(){const q=new URLSearchParams(location.search);const sensor=q.get('sensor');if(sensor)setSensor(sensor);if(q.get('detect')==='1'&&!S.detection)toggleDetection();if(q.get('scope')==='1'&&!S.scope)toggleScope();if(q.get('hud')==='0')document.body.classList.add('sup-hud-off');const cam=(q.get('cam')||'').split(',').map(Number);if(cam.length===6&&cam.every(Number.isFinite)){getViewer()?.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cam[0],cam[1],cam[2]),orientation:{heading:Cesium.Math.toRadians(cam[3]),pitch:Cesium.Math.toRadians(cam[4]),roll:Cesium.Math.toRadians(cam[5])}})}}
function capture(){const v=getViewer();if(!v)return toast('Open Live Earth first');try{v.scene.render();const a=document.createElement('a');a.download=`xunia-geospatial-${Date.now()}.png`;a.href=v.scene.canvas.toDataURL('image/png');a.click();toast('Snapshot saved')}catch{toast('Snapshot blocked by map tile CORS') }}
function saveBookmark(){const cam=cameraState();if(!cam)return toast('Open Live Earth first');const list=JSON.parse(localStorage.getItem('xunia:geo-bookmarks:v1')||'[]');list.unshift({name:`View ${new Date().toLocaleString()}`,cam,sensor:S.sensor});localStorage.setItem('xunia:geo-bookmarks:v1',JSON.stringify(list.slice(0,24)));toast('Camera bookmark saved');if(S.drawer==='bookmarks')renderBookmarks()}
function renderBookmarks(){const body=$('#supDrawerBody');if(!body)return;const list=JSON.parse(localStorage.getItem('xunia:geo-bookmarks:v1')||'[]');$('#supDrawerCount')&&($('#supDrawerCount').textContent=`${list.length} SAVED`);body.innerHTML=list.map((b,i)=>`<div class="sup-contact" data-bookmark="${i}"><div><b>${escape(b.name)}</b><span>${escape((b.sensor||'normal').toUpperCase())}</span></div><i>LOAD</i></div>`).join('')||'<div class="empty-state"><b>NO BOOKMARKS</b><span>Save a camera view.</span></div>';[...body.querySelectorAll('[data-bookmark]')].forEach(el=>el.onclick=async()=>{const b=list[Number(el.dataset.bookmark)];await ensureEarth();const cam=b.cam.split(',').map(Number);getViewer().camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(cam[0],cam[1],cam[2]),orientation:{heading:Cesium.Math.toRadians(cam[3]),pitch:Cesium.Math.toRadians(cam[4]),roll:Cesium.Math.toRadians(cam[5])},duration:1});setSensor(b.sensor||'normal')})}

function openSettings(){$('#supSettingsShade')?.classList.add('open');$('#supCesiumToken')&&( $('#supCesiumToken').value=sessionStorage.getItem('xunia:cesium-token')||'');$('#supGoogleKey')&&( $('#supGoogleKey').value=sessionStorage.getItem('xunia:google-key')||'')}
function closeSettings(){$('#supSettingsShade')?.classList.remove('open')}
async function powerUp(){const v=await ensureEarth();const token=$('#supCesiumToken')?.value.trim()||'';const google=$('#supGoogleKey')?.value.trim()||'';if(token){sessionStorage.setItem('xunia:cesium-token',token);Cesium.Ion.defaultAccessToken=token;try{v.terrainProvider=await Cesium.createWorldTerrainAsync();toast('Cesium World Terrain enabled')}catch(e){toast(`Terrain unavailable: ${e.message}`)}}if(google){sessionStorage.setItem('xunia:google-key',google);try{if(S.photoreal)v.scene.primitives.remove(S.photoreal);S.photoreal=await Cesium.createGooglePhotorealistic3DTileset({key:google});v.scene.primitives.add(S.photoreal);v.scene.globe.show=false;toast('Photorealistic 3D enabled')}catch(e){toast(`Google 3D unavailable: ${e.message}`)}}closeSettings()}

function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Browser voice recognition unavailable');const r=new R();r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;readout('VOICE LISTENING','LOCAL COMMAND PARSER');r.onresult=e=>{const text=e.results[0][0].transcript.trim();toast(`VOICE: ${text}`);handleVoice(text)};r.onerror=e=>toast(`Voice: ${e.error}`);r.start()}
function handleVoice(text){const t=text.toLowerCase();if(/reset globe|zoom out|go home/.test(t))return $('#homeBtn')?.click();if(/global context|show everything/.test(t))return setGlobalContext();if(/show contacts|nearby contacts/.test(t))return openDrawer('contacts');if(/track (it|target|contact)/.test(t))return trackSelected();if(/cockpit/.test(t))return cockpit();if(/turn .*detection|detection on/.test(t))return !S.detection&&toggleDetection();if(/detection off/.test(t))return S.detection&&toggleDetection();for(const mode of sensorModes){if(t.includes(mode)||mode==='flir'&&t.includes('thermal')||mode==='nvg'&&t.includes('night vision'))return setSensor(mode)}const layer=Object.keys(layerAlias).find(k=>t.includes(k));if(layer){const id=layerAlias[layer],b=$(`[data-layer="${id}"]`);if(b){const wantOff=/off|disable|hide/.test(t);const on=b.classList.contains('active');if((wantOff&&on)||(!wantOff&&!on))b.click();return toast(`${id} ${wantOff?'off':'on'}`)}}const m=t.match(/(?:go to|take me to|search for|find)\s+(.+)/);if(m)return geocode(m[1]);toast('Command not recognized')}

function refreshLiveLayers(){if(S.refreshing||!getViewer())return;S.refreshing=true;const ids=['flights','maritime','sat_military','cctv','live_news','weather','earthquakes','fires','global_incidents','launches','radio','bikeshare','traffic'];let delay=0;for(const id of ids){const b=$(`[data-layer="${id}"]`);if(!b?.classList.contains('active'))continue;setTimeout(()=>{b.click();setTimeout(()=>b.click(),350)},delay);delay+=140}setTimeout(()=>{S.refreshing=false;renderContacts()},Math.max(1200,delay+700))}
function wire(){
  $('#supContacts')?.addEventListener('click',()=>openDrawer('contacts'));$('#supDrawerClose')?.addEventListener('click',closeDrawer);$('#supTrack')?.addEventListener('click',trackSelected);$('#supCockpit')?.addEventListener('click',cockpit);$('#supContext')?.addEventListener('click',setGlobalContext);$('#supDetect')?.addEventListener('click',toggleDetection);$('#supScope')?.addEventListener('click',toggleScope);$('#supHud')?.addEventListener('click',toggleHud);$('#supDirector')?.addEventListener('click',toggleDirector);$('#sup3d')?.addEventListener('click',toggle2D3D);$('#supDraw')?.addEventListener('click',()=>beginDraw('draw'));$('#supMeasure')?.addEventListener('click',()=>beginDraw('measure'));$('#supClear')?.addEventListener('click',clearAnnotations);$('#supShare')?.addEventListener('click',shareView);$('#supCapture')?.addEventListener('click',capture);$('#supVoice')?.addEventListener('click',startVoice);$('#supSettings')?.addEventListener('click',openSettings);$('#supSettingsClose')?.addEventListener('click',closeSettings);$('#supPowerUp')?.addEventListener('click',powerUp);$('#supBasemap')?.addEventListener('click',toggleBasemap);$('#supBookmark')?.addEventListener('click',saveBookmark);$('#supBookmarks')?.addEventListener('click',()=>openDrawer('bookmarks'));$$('[data-sensor]').forEach(b=>b.onclick=()=>setSensor(b.dataset.sensor));
  const search=$('#globalSearch');search?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();geocode(search.value)}});
  window.addEventListener('keydown',e=>{if(document.activeElement?.matches('input,textarea'))return;if(/^[1-7]$/.test(e.key))setSensor(sensorModes[Number(e.key)-1]);if(e.key.toLowerCase()==='h')toggleHud();if(e.key.toLowerCase()==='c')cockpit();if(e.key.toLowerCase()==='f')$('[data-layer="flights"]')?.click();if(e.key.toLowerCase()==='s')$('[data-layer="sat_military"]')?.click();if(e.key.toLowerCase()==='b'&&e.shiftKey)saveBookmark()});
  setInterval(()=>{if($('#supDrawer')?.classList.contains('open')&&S.drawer==='contacts')renderContacts()},8000);setInterval(refreshLiveLayers,120000);
}
wire();
